### ISSUE TITLE
2.1.0 - Content-Length no longer present in response's specs

### ISSUE THREAD

**Issue by erwanlr** [rack/rack#1472]
After updating to 2.1.0, all my tests checking for the `Content-Length` header in responses are failing. It seems like the header is not set anymore somehow.

Here is an example:

```ruby
# config.ru
# frozen_string_literal: true

run lambda { |_| [200, {}, ['Hello, world!']] }
```

```ruby
# spec.rb
require 'rspec'
require 'rspec/its'
require 'rack'
require 'rack/test'

RSpec.configure do |config|
  config.include Rack::Test::Methods
end

describe 'App' do
  def app
    Rack::Builder.parse_file('config.ru').first
  end

  context 'when GET /' do
    subject(:res) { get('/') }

    its(:status) { is_expected.to be 200 }
    its(:headers) { are_expected.to include('Content-Length' => '13') }
    its(:body) { is_expected.to eql 'Hello, world!' }
  end
end
```

```ruby
# test.rb
require 'minitest/global_expectations/autorun'
require 'rack/mock'

describe 'App' do
  def app
    Rack::Builder.parse_file('config.ru').first
  end

  def request
    Rack::MockRequest.new(app)
  end

  it 'GET /' do
    response = request.get('/')

    response.status.must_equal 200
    response.header['Content-Length'].must_equal '13'
    response.body.must_equal 'Hello, world!'
  end
end
```

Gemfile
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rack', '~> 2.1.1'
#gem 'rack', git: 'https://github.com/rack/rack.git'

gem 'rack-test', '~> 1.1.0'
gem 'rspec', '~> 3.9.0'
gem 'rspec-its', '~> 1.3.0'

gem 'minitest', '~> 5.14.0'
gem 'minitest-global_expectations', '~> 1.0.1'
```

Put these files in a same directory and run` rspec spec.rb` if using RSpec or `bundle exec ruby test.rb` to use Minitest

Output with Rack 2.1.0, and Rack-Test 1.1.0:
```
$ rspec spec.rb 
.F.

Failures:

  1) App when GET / headers is expected to include {"Content-Length" => "10"}
     Failure/Error: its(:headers) { are_expected.to include('Content-Length' => '10') }
     
       expected {} to include {"Content-Length" => "10"}
       Diff:
       @@ -1,2 +1 @@
       -"Content-Length" => "10",
       
     # ./spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 0.04414 seconds (files took 0.16756 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec.rb:19 # App when GET / headers is expected to include {"Content-Length" => "10"}
```

Output with Rack 2.0.8 and Rack-Test 1.1.0:

```
$ rspec spec.rb 
...

Finished in 0.02087 seconds (files took 0.13891 seconds to load)
3 examples, 0 failures
```

I don't really know where the issue comes from, but if I put `use Rack::ContentLength` in the config.ru, specs pass with 2.1.0.

**Comment by ioquatix** [comment]
Where are you expecting content-length header to come from? Was there some implicit middleware before that is no longer present?

**Comment by ioquatix** [comment]
It seems like the behaviour of `rackup` in my specs changed as well.

```
     1.1) Failure/Error: expect(response.read).to be == "Hello World"

            expected: == "Hello World"
                 got:    "b\r\nHello World\r\n0\r\n\r\n"
```

This seems to imply a lack of `transfer-encoding` header.

**Comment by erwanlr** [comment]
All I did was update Rack from 2.0.8 to 2.1.0, ran the specs and got some failures. There was some middleware involved in my real case scenario, yes. However, I managed to get a minimum example to reproduce the issue to provide that here w/o any middleware and so on so that you can check that w/o having to dig into a bigger app and stuff ^^.

I don't think it's the responsibility of a middleware to get the Content-Length right, but rather the server, however as there was nothing in the changelog about such change for 2.1.0, I would put that as a regression.

**Comment by ioquatix** [comment]
After 3 years of PRs we can only do our best, unfortunately something has obviously slipped through the cracks.

I'll see if we can't fix this in a 2.1.1 release.

**Comment by erwanlr** [comment]
No worries, it only happen in specs by the looks of it (as running `rackup` will add some middleware like the ContentLength one, and running it w/o a valid env, like `rackup -E prod` will have the server put the ContentLength by itself - at least with WEBrick. However, as in the specs the server it not running, well, boom.)

Which brings me to a question, with the example in my first post, how could I use a supported server (let's say WEBrick) to serve the app to be able to fully test it ?

**Comment by ioquatix** [comment]
Okay, I figured out at least partially what's going on.

For a long time, `Rack::Chunked` has been broken, I think it's `HTTP_VERSION` detection was borked. A recent PR seems to have fixed it, and now it's applying is behaviour more liberally, which is deleting the content length and sending the data using chunked encoding.

```
git diff 2.0.8 2.1.0 lib/rack/chunked.rb
```

![image](https://user-images.githubusercontent.com/30030/72210312-330cf680-351e-11ea-856e-b35b0a43a014.png)

I'm going to take a guess that `! chunkable_version?(env[SERVER_PROTOCOL])` is now working correctly... and never was before.

cc @tenderlove @rafaelfranca 

Possible solutions:

- Remove `Rack::Chunked` from default middleware in `Rack::Server`.
- ???

**Comment by ioquatix** [comment]
Can you please try with latest master which removes `Rack::Chunked` from the default stack and let me know if that fixes your issues?

**Comment by erwanlr** [comment]
Nop, did not fix it (tested with v2.2.0 from master)

**Comment by ioquatix** [comment]
Damn. Can you make a small repro?

**Comment by ioquatix** [comment]
We've just release 2.1.1 can you please try that.

**Comment by erwanlr** [comment]
Nop, still have the issue.

> Can you make a small repro?

If you mean a way to reproduce the issue, it has been provided in the first post. I just edited it to also provide a test file to use with Minitest like done in this project.

Both tests (using RSpec and Minitest) pass with 2.0.8 but fail with 2.1.0+. It seems that the cause is this commit: https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e

**Comment by ioquatix** [comment]
Okay I am currently on holiday. Can you make a PR with a failing spec based on your repro.

**Comment by jeremyevans** [comment]
In 2.0.8, the `Content-Length` response header is added in `Rack::Response#initialize` when it takes the body argument and writes to the internal body of the response.  In 2.1+, the body argument is used directly as the internal body of the response. This change was deliberate for performance, made in 8c62821f4a464858a6b6ca3c3966ec308d2bb53e.  The previous implementation updated the `Content-Length` header for every string yielded by body.each (if the body argument was not a string).

I think the previous behavior of setting the `Content-Length` was an implementation detail of `Rack::Response`.  If you want to set the `Content-Length` response header, use the `Rack::ContentLength` middleware (`simple_app = Rack::ContentLength.new(simple_app)` in your example).  I believe setting the `Content-Length` should be done by the app or middleware, not `Rack::Response`, though that is certainly a matter of opinion.

I do not think this is a bug, so I'll be closing it in a few days unless another core team member disagrees.

**Comment by ioquatix** [comment]
That’s a good summary. FYI, it wasn’t just for performance. It’s to avoid messing with bodies that don’t support `#each` like websockets.

**Comment by lsirivong** [comment]
👋 Hello, I'm seeing something similar which arises from building middleman projects:

Here's an example middleman project which fails to build when `activate :asset_host` config is used.

https://github.com/lsirivong/middleman-example

```log
16:35 ~/src/middleman-example (master)
🔮  middleman build --verbose
WARN: Unresolved or ambigious specs during Gem::Specification.reset:
      minitest (~> 5.1)
      Available/installed versions of this gem:
      - 5.14.0
      - 5.11.3
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
== Activating: file_watcher
== Activating: front_matter
== Activating: data
== Activating: inline_url_rewriter
== Activating: sitemap_ondisk
== Activating: sitemap_import
== Activating: sitemap_endpoint
== Activating: sitemap_proxies
== Activating: sitemap_redirects
== Activating: sitemap_move_files
== Activating: sitemap_ignore
== Activating: external_helpers
== Activating: erb_renderer
== Activating: coffee_renderer
== Activating: haml_renderer
== Activating: sass_renderer
== Activating: markdown_renderer
== Failed Activation `liquid_renderer` : cannot load such file -- liquid
== Failed Activation `slim_renderer` : cannot load such file -- slim
== Failed Activation `less_renderer` : cannot load such file -- less
== Failed Activation `stylus_renderer` : cannot load such file -- stylus
== Activating: default_helpers
== Activating: lorem
== Activating: routing
== Activating: collections
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): images/.keep
== Change (#<Set: {:source}>): layouts/layout.erb
== Change (#<Set: {:source}>): javascripts/site.js
== Change (#<Set: {:source}>): stylesheets/site.css.scss
== Rebuilding resource list
== Reading: Local config: config.rb
== Activating: autoprefixer
== Requesting resource list rebuilding: first_run_change_page
== Requesting resource list rebuilding: first_run_change_page
== Requesting resource list rebuilding: first_run_change_page
== Activating: asset_host
Loaded extensions:
== Extension: file_watcher
== Extension: front_matter
== Extension: data
== Extension: inline_url_rewriter
== Extension: sitemap_ondisk
== Extension: sitemap_import
== Extension: sitemap_endpoint
== Extension: sitemap_proxies
== Extension: sitemap_redirects
== Extension: sitemap_move_files
== Extension: sitemap_ignore
== Extension: external_helpers
== Extension: erb_renderer
== Extension: coffee_renderer
== Extension: haml_renderer
== Extension: sass_renderer
== Extension: markdown_renderer
== Extension: default_helpers
== Extension: lorem
== Extension: routing
== Extension: collections
== Extension: autoprefixer
== Extension: asset_host
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): images/.keep
== Change (#<Set: {:source}>): layouts/layout.erb
== Change (#<Set: {:source}>): javascripts/site.js
== Change (#<Set: {:source}>): stylesheets/site.css.scss
== Rebuilding resource list
== Requesting resource list rebuilding: touched_file
== Requesting resource list rebuilding: registered_new_manipulator_front_matter
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ondisk
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_import
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_endpoint
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_proxies
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_redirects
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_move_files
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ignore
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_collections
== Rebuilding resource list
== Running manipulator: sitemap_ondisk (0)
== Running manipulator: sitemap_endpoint (0)
== Running manipulator: sitemap_proxies (0)
== Running manipulator: sitemap_redirects (0)
== Running manipulator: sitemap_ignore (0)
== Running manipulator: sitemap_import (1)
== Running manipulator: routing (10)
== Running manipulator: front_matter (20)
== Running manipulator: sitemap_move_files (101)
== Running manipulator: collections (110)
== Running manipulator: routing (130)
== Prerendering CSS
== Request: /stylesheets/site.css
== Finishing Request: stylesheets/site.css (0.02s)
   identical  build/stylesheets/site.css
== Building files
== Request: /index.html
== Request: /javascripts/site.js
== Request: /images/.keep
== Finishing Request: javascripts/site.js (0.0s)
== Finishing Request: images/.keep (0.0s)
   identical  build/javascripts/site.js
   identical  build/images/.keep
== Finishing Request: index.html (0.02s)
       error  build/index.html
Content-Length header was 1435, but should be 1485
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/lint.rb:22:in `assert'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/lint.rb:695:in `verify_content_length'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/lint.rb:719:in `each'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/response.rb:236:in `buffered_body!'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/mock.rb:173:in `initialize'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/mock.rb:78:in `new'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/mock.rb:78:in `request'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/mock.rb:59:in `get'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:232:in `block in output_resource'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:225:in `output_resource'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:507:in `call_with_index'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:471:in `process_incoming_jobs'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:453:in `block in worker'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:444:in `fork'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:444:in `worker'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:435:in `block in create_workers'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `each'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `each_with_index'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `create_workers'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:373:in `work_in_processes'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:277:in `map'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:137:in `output_resources'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:131:in `output_files'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:70:in `run!'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:84:in `block in build'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:21:in `instrument'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:83:in `build'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
source 'https://rubygems.org'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:40:in `block in register'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/Users/lennysirivong/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.5/bin/middleman:70:in `<top (required)>'
/Users/lennysirivong/.rbenv/versions/2.6.3/bin/middleman:23:in `load'
/Users/lennysirivong/.rbenv/versions/2.6.3/bin/middleman:23:in `<main>'
There were errors during this build
```

I've added another branch to that repo which downgrades to 2.0.8, which does not fail to build:

https://github.com/lsirivong/middleman-example/tree/rack-2.0.8

```log
16:36 ~/src/test-middleman (rack-2.0.8)
🔮  middleman build --verbose
WARN: Unresolved or ambigious specs during Gem::Specification.reset:
      rack (>= 1.4.5, < 3)
      Available/installed versions of this gem:
      - 2.1.1
      - 2.0.8
      minitest (~> 5.1)
      Available/installed versions of this gem:
      - 5.14.0
      - 5.11.3
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
== Activating: file_watcher
== Activating: front_matter
== Activating: data
== Activating: inline_url_rewriter
== Activating: sitemap_ondisk
== Activating: sitemap_import
== Activating: sitemap_endpoint
== Activating: sitemap_proxies
== Activating: sitemap_redirects
== Activating: sitemap_move_files
== Activating: sitemap_ignore
== Activating: external_helpers
== Activating: erb_renderer
== Activating: coffee_renderer
== Activating: haml_renderer
== Activating: sass_renderer
== Activating: markdown_renderer
== Failed Activation `liquid_renderer` : cannot load such file -- liquid
== Failed Activation `slim_renderer` : cannot load such file -- slim
== Failed Activation `less_renderer` : cannot load such file -- less
== Failed Activation `stylus_renderer` : cannot load such file -- stylus
== Activating: default_helpers
== Activating: lorem
== Activating: routing
== Activating: collections
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): images/.keep
== Change (#<Set: {:source}>): layouts/layout.erb
== Change (#<Set: {:source}>): javascripts/site.js
== Change (#<Set: {:source}>): stylesheets/site.css.scss
== Rebuilding resource list
== Reading: Local config: config.rb
== Activating: autoprefixer
== Requesting resource list rebuilding: first_run_change_page
== Requesting resource list rebuilding: first_run_change_page
== Requesting resource list rebuilding: first_run_change_page
== Activating: asset_host
Loaded extensions:
== Extension: file_watcher
== Extension: front_matter
== Extension: data
== Extension: inline_url_rewriter
== Extension: sitemap_ondisk
== Extension: sitemap_import
== Extension: sitemap_endpoint
== Extension: sitemap_proxies
== Extension: sitemap_redirects
== Extension: sitemap_move_files
== Extension: sitemap_ignore
== Extension: external_helpers
== Extension: erb_renderer
== Extension: coffee_renderer
== Extension: haml_renderer
== Extension: sass_renderer
== Extension: markdown_renderer
== Extension: default_helpers
== Extension: lorem
== Extension: routing
== Extension: collections
== Extension: autoprefixer
== Extension: asset_host
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): images/.keep
== Change (#<Set: {:source}>): layouts/layout.erb
== Change (#<Set: {:source}>): javascripts/site.js
== Change (#<Set: {:source}>): stylesheets/site.css.scss
== Rebuilding resource list
== Requesting resource list rebuilding: touched_file
== Requesting resource list rebuilding: registered_new_manipulator_front_matter
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ondisk
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_import
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_endpoint
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_proxies
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_redirects
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_move_files
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ignore
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_collections
== Rebuilding resource list
== Running manipulator: sitemap_ondisk (0)
== Running manipulator: sitemap_endpoint (0)
== Running manipulator: sitemap_proxies (0)
== Running manipulator: sitemap_redirects (0)
== Running manipulator: sitemap_ignore (0)
== Running manipulator: sitemap_import (1)
== Running manipulator: routing (10)
== Running manipulator: front_matter (20)
== Running manipulator: sitemap_move_files (101)
== Running manipulator: collections (110)
== Running manipulator: routing (130)
== Prerendering CSS
== Request: /stylesheets/site.css
== Finishing Request: stylesheets/site.css (0.01s)
   identical  build/stylesheets/site.css
== Building files
== Request: /javascripts/site.js
== Request: /index.html
== Request: /images/.keep
== Finishing Request: javascripts/site.js (0.0s)
== Finishing Request: images/.keep (0.0s)
   identical  build/javascripts/site.js
   identical  build/images/.keep
== Finishing Request: index.html (0.02s)
     updated  build/index.html
Project built successfully.
```

**Comment by jeremyevans** [comment]
@lsirivong The relevant error line appears to be `Content-Length header was 1435, but should be 1485`.  This indicates middleman is calculating the content length incorrectly, probably using `String#size` instead of `String#bytesize` if I had to guess.  Looks like a bug in middleman that should be fixed by them, which was hidden by Rack::Responses's previous implementation.

**Comment by lsirivong** [comment]
@jeremyevans thanks for the prompt response! I've posted an issue on the middleman repo.

**Comment by tanelsuurhans** [comment]
I am running into a similar issue with a Rails 5.1.7 app where nginx keeps complaining that the Content-Length from upstream is off, and the header is also not delivered to the client at all.

@jeremyevans do I understand correctly that we should then be applying the Rack::ContentLength middleware manually?

**Comment by jeremyevans** [comment]
If your application does not correctly calculate the Content-Length header when returning the response array, the easiest fix is using Rack::ContentLength.

**Comment by Stivaros** [comment]
I've just had this issue working on a Rails 5.1.4 app (although I tested and it was still an issue with Rails 5.1.7) with Rack 2.2.3/2.1.0 (having initially used 2.0.4). I circled around it a few times as `Rack::ContentLength` was also returning the same (_incorrect_) `'Content-Length'`. I had considered them both returning the same figure to be confirmation they were both working whereas it was basically a false positive and they were both wrong.

In case it may help others, the solution I went with was to use `Rack::Deflater`, which I'm happily considering a double-win. It gets rid of the erroneous `'Content-Length'` header _and_ it provides me with all the happy benefits of gzip compression.

An alternative would be to write some custom middleware or monkey-patch `Rack::ContentLength` so that the header is recalculated in all cases, I think.

Hope these notes help.

**Comment by ioquatix** [comment]
Why was your app returning the incorrect content length?

**Comment by Stivaros** [comment]
To be honest, I didn't spend much time dwelling on that but happily attributed it to #1615 (and the underlying Ruby bug).

I can easily revert the change and test anything you may have an interest in me investigating but I cannot provide a copy of the repo for you to test, unfortunately.
